// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdeachx-e-aW6SRgQ0JbWHfbVGEuxAnN0',
    appId: '1:421595305713:web:108b47d1cef872b2803b50',
    messagingSenderId: '421595305713',
    projectId: 'bmi-calculater-task',
    authDomain: 'bmi-calculater-task.firebaseapp.com',
    storageBucket: 'bmi-calculater-task.appspot.com',
    measurementId: 'G-7FYDW0Q0QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjAQsU_sV7NvnGeFrTeiBP8VXpRk3JadA',
    appId: '1:421595305713:android:d7e3cc142419f816803b50',
    messagingSenderId: '421595305713',
    projectId: 'bmi-calculater-task',
    storageBucket: 'bmi-calculater-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeN3FtbIl-fgfazqu0LTi_gCFslqLCDrg',
    appId: '1:421595305713:ios:6451a4b3db0c4c1c803b50',
    messagingSenderId: '421595305713',
    projectId: 'bmi-calculater-task',
    storageBucket: 'bmi-calculater-task.appspot.com',
    iosBundleId: 'com.example.bmiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeN3FtbIl-fgfazqu0LTi_gCFslqLCDrg',
    appId: '1:421595305713:ios:6451a4b3db0c4c1c803b50',
    messagingSenderId: '421595305713',
    projectId: 'bmi-calculater-task',
    storageBucket: 'bmi-calculater-task.appspot.com',
    iosBundleId: 'com.example.bmiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdeachx-e-aW6SRgQ0JbWHfbVGEuxAnN0',
    appId: '1:421595305713:web:d18b6d0668068c46803b50',
    messagingSenderId: '421595305713',
    projectId: 'bmi-calculater-task',
    authDomain: 'bmi-calculater-task.firebaseapp.com',
    storageBucket: 'bmi-calculater-task.appspot.com',
    measurementId: 'G-JV5GSSCEZM',
  );
}
